In [ ]:
sentences = ["I feel proud to be a citizen of India because of its rich culture, traditions, and history.",
"It is known for its festivals, traditions, and historical monuments.",
"India is the world’s largest democracy.",

"Technology makes our work easier and faster.",
"It helps us communicate and learn better.",
"Modern life depends heavily on technology.",

"Sports help people stay healthy and active.",
"They teach teamwork, discipline, and confidence.",
"in my free time i would love to play cricket."
]

In [ ]:
#importing the libraries
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer #TF-Bow
from sklearn.feature_extraction.text import TfidfVectorizer #TFIDF
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
#Embeddings using TF_Bow approach
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sentences)
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 72 stored elements and shape (9, 60)>

In [ ]:
tfidf_similarity=cosine_similarity(tfidf_matrix)
tfidf_similarity


array([[1.        , 0.15310398, 0.07874408, 0.02841468, 0.02841468,
        0.        , 0.02775765, 0.03027674, 0.06214335],
       [0.15310398, 1.        , 0.10744065, 0.03876979, 0.14108832,
        0.        , 0.03787332, 0.04131044, 0.        ],
       [0.07874408, 0.10744065, 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.02841468, 0.03876979, 0.        , 1.        , 0.04517405,
        0.12200786, 0.0441295 , 0.04813438, 0.        ],
       [0.02841468, 0.14108832, 0.        , 0.04517405, 1.        ,
        0.        , 0.0441295 , 0.04813438, 0.        ],
       [0.        , 0.        , 0.        , 0.12200786, 0.        ,
        1.        , 0.        , 0.        , 0.        ],
       [0.02775765, 0.03787332, 0.        , 0.0441295 , 0.0441295 ,
        0.        , 1.        , 0.04702137, 0.        ],
       [0.03027674, 0.04131044, 0.        , 0.04813438, 0.04813438,
        0.        , 0.04702137, 1.        , 0.        ],


In [ ]:
#finding out the document similarity
def doc_sim(similarity_matrix,sentences):
  for i in range(len(sentences)):
    sims=similarity_matrix[i].copy()
    sims[i]=-1
    sims=sims.max()
    top_index=np.argmax(sims)
    print(sentences[i],"-->",sentences[top_index])

In [ ]:
doc_sim(tfidf_similarity,sentences)

I feel proud to be a citizen of India because of its rich culture, traditions, and history. --> I feel proud to be a citizen of India because of its rich culture, traditions, and history.
It is known for its festivals, traditions, and historical monuments. --> I feel proud to be a citizen of India because of its rich culture, traditions, and history.
India is the world’s largest democracy. --> I feel proud to be a citizen of India because of its rich culture, traditions, and history.
Technology makes our work easier and faster. --> I feel proud to be a citizen of India because of its rich culture, traditions, and history.
It helps us communicate and learn better. --> I feel proud to be a citizen of India because of its rich culture, traditions, and history.
Modern life depends heavily on technology. --> I feel proud to be a citizen of India because of its rich culture, traditions, and history.
Sports help people stay healthy and active. --> I feel proud to be a citizen of India because

In [ ]:
corpus = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love coding in python"
]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize vectorizer
bow = CountVectorizer()

# Fit and transform
X_bow = bow.fit_transform(corpus)

# Convert to array
bow_array = X_bow.toarray()

# Get feature names
features = bow.get_feature_names_out()

# Print results
print("Vocabulary:", features)
print("\nBoW Matrix:\n", bow_array)

Vocabulary: ['amazing' 'coding' 'in' 'is' 'learning' 'love' 'machine' 'python']

BoW Matrix:
 [[0 0 0 0 1 1 1 0]
 [1 0 0 1 1 0 1 0]
 [0 1 1 0 0 1 0 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Use TF only (disable IDF)
tf = TfidfVectorizer(use_idf=False, norm='l1')

# Fit and transform
X_tf = tf.fit_transform(corpus)

# Convert to array
tf_array = X_tf.toarray()

# Get feature names
features_tf = tf.get_feature_names_out()

# Print results
print("Vocabulary:", features_tf)
print("\nTF Matrix:\n", tf_array)

Vocabulary: ['amazing' 'coding' 'in' 'is' 'learning' 'love' 'machine' 'python']

TF Matrix:
 [[0.         0.         0.         0.         0.33333333 0.33333333
  0.33333333 0.        ]
 [0.25       0.         0.         0.25       0.25       0.
  0.25       0.        ]
 [0.         0.25       0.25       0.         0.         0.25
  0.         0.25      ]]


In [ ]:
documents = [
    "I love machine learning",

    "Machine learning is amazing",
    "I enjoy coding in python"
]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# BoW
bow = CountVectorizer()
X_bow = bow.fit_transform(documents)

# Similarity
bow_similarity = cosine_similarity(X_bow)

print("BoW Similarity Matrix:\n", bow_similarity)

BoW Similarity Matrix:
 [[1.         0.57735027 0.        ]
 [0.57735027 1.         0.        ]
 [0.         0.         1.        ]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# TF (no IDF)
tf = TfidfVectorizer(use_idf=False, norm='l2')
X_tf = tf.fit_transform(documents)

# Similarity
tf_similarity = cosine_similarity(X_tf)

print("TF Similarity Matrix:\n", tf_similarity)

TF Similarity Matrix:
 [[1.         0.57735027 0.        ]
 [0.57735027 1.         0.        ]
 [0.         0.         1.        ]]


In [ ]:
# TF-IDF
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(documents)

# Similarity
tfidf_similarity = cosine_similarity(X_tfidf)

print("TF-IDF Similarity Matrix:\n", tfidf_similarity)

TF-IDF Similarity Matrix:
 [[1.         0.44333251 0.        ]
 [0.44333251 1.         0.        ]
 [0.         0.         1.        ]]
